# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_auto_20180816_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonImportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('problem_name', models.CharField(max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', oioioi.base.fields.EnumField(default='QU', max_length=64)),
                ('info', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
    ]
