# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonimportrequest',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
