# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.problems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemHooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=oioioi.problems.models.make_problem_filename)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
    ]
