# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinol2pack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemhooks',
            name='type',
            field=models.TextField(choices=[('compile', 'Haczyk kompilacji'), ('run', 'Haczyk uruchomienia')], default='compile', max_length=8),
            preserve_default=False,
        ),
    ]
