# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0005_submission_auto_rejudges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiler', models.CharField(choices=[(b'GCC 4.6 (32 bits)', b'compiler-gcc.4_6_3'), (b'GCC 4.8 (32 bits)', b'compiler-gcc.4_8_2'), (b'GCC 8.3 (32 bits)', b'compiler-gcc.8_3_0-i386'), (b'GCC 8.3 (64 bits)', b'compiler-gcc.8_3_0-amd64')], default=b'compiler-gcc.4_8_2', max_length=128)),
                ('cflags', models.CharField(default=b'-std=gnuc99 -static -O2 -s -lm', max_length=256)),
                ('cxxflags', models.CharField(default=b'-std=c++11 -static -O2 -s -lm', max_length=256)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
    ]
