# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cconfiguration',
            name='compiler',
            field=models.CharField(choices=[(b'gcc.4_6_3', b'GCC 4.6 (32 bits)'), (b'gcc.4_8_2', b'GCC 4.8 (32 bits)'), (b'gcc.8_3_0-amd64', b'GCC 8.3 (64 bits)'), (b'gcc.8_3_0-i386', b'GCC 8.3 (32 bits)')], default=b'gcc.4_8_2', max_length=128),
        ),
    ]
