# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-18 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cconf', '0002_auto_20191015_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cconfiguration',
            name='cflags',
            field=models.CharField(default=b'-std=gnu99 -static -O2 -s -lm', max_length=256),
        ),
    ]
