# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_acm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmrankingconfig',
            name='round',
        ),
    ]
