# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_acm', '0002_remove_acmrankingconfig_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmrankingconfig',
            name='ranking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking'),
        ),
    ]
