# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_acm', '0003_auto_20180828_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmrankingconfig',
            name='unfreeze',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
