# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judging',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
