# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180816_2112'),
        ('feedback', '0002_judging_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'Do not show judgings table'), ('pro', 'Show judging progress table'), ('all', 'Show judging progress and results table')], default='pro', max_length=3)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
            options={
                'verbose_name': 'SmartJudge\u2122 Judging table',
                'verbose_name_plural': 'SmartJudge\u2122 Judging table',
            },
        ),
    ]
