# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_judgingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartjudgeconfig',
            name='mode',
            field=models.CharField(choices=[('off', 'Always judge all tests'), ('on', "Do not judge tests that don't affect score")], default='on', max_length=3),
        ),
    ]
