# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-25 21:08
from __future__ import unicode_literals

from django.db import migrations
import staszic.languages


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageconfig',
            name='languages_desc',
            field=staszic.languages.LanguageSelectionField(),
        ),
    ]
