# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0009_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_name', oioioi.base.fields.DottedNameField(choices=[(b'dummy', b'Dummy')], superclass='staszic.rankings.ranking_types.RankingTypeBase')),
                ('last_calculation', models.DateTimeField(blank=True, null=True)),
                ('serialized_data', models.TextField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
    ]
