# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_auto_20180816_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedRankingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=256, verbose_name='Round name')),
                ('start_date', models.DateTimeField(verbose_name='Ignore submissions before')),
                ('end_date', models.DateTimeField(verbose_name='Ignore submissions after')),
                ('column_visibility', models.CharField(choices=[('never', 'Never visible'), ('end', 'Visible after the round ends'), ('results', 'Visible as the round results become visible'), ('always', 'Visible after the round starts')], default='end', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RoundRankingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_coef', models.IntegerField(default=1, verbose_name='Contest coefficient')),
                ('round_type', models.CharField(choices=[('best', 'Best'), ('last', 'Last'), ('rlast', 'Last + revealed')], default='last', max_length=8, verbose_name='Contest scoring type')),
                ('contest_coef', models.IntegerField(default=0, verbose_name='All-time coefficient')),
                ('contest_type', models.CharField(choices=[('best', 'Best'), ('last', 'Last'), ('rlast', 'Last + revealed')], default='best', max_length=8, verbose_name='All-time scoring type')),
                ('column_visibility', models.CharField(choices=[('never', 'Never visible'), ('end', 'Visible after the round ends'), ('results', 'Visible as the round results become visible'), ('always', 'Visible after the round starts')], default='end', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_name', oioioi.base.fields.DottedNameField(choices=[(b'dummy', b'Dummy')], superclass='staszic.rankings.ranking_types.RankingTypeBase')),
                ('renderer_name', oioioi.base.fields.DottedNameField(choices=[(b'dummy', b'Dummy')], superclass='staszic.rankings.ranking_renderers.RankingRendererBase')),
                ('last_calculation', models.DateTimeField(blank=True, null=True)),
                ('serialized_data', models.TextField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryRankingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_sum', models.BooleanField(default=True)),
                ('show_percentage', models.BooleanField(default=False)),
                ('show_difference', models.BooleanField(default=False)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
        migrations.CreateModel(
            name='TableRendererConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medals', models.CharField(choices=[('none', 'No medals'), ('ioi', 'IOI - 1/12 golds, 1/6 silver, 1/4 bronze'), ('og', '1 gold, 1 silver, 1 bronze')], default='none', max_length=8)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
        migrations.AddField(
            model_name='roundrankingconfig',
            name='ranking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking'),
        ),
        migrations.AddField(
            model_name='advancedrankingconfig',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking'),
        ),
    ]
