# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrankingconfig',
            name='round',
            field=models.CharField(default='', max_length=256, verbose_name='Round name'),
            preserve_default=False,
        ),
    ]
