# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-01 07:53
from __future__ import unicode_literals

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20180318_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicranking',
            name='renderer_name',
            field=oioioi.base.fields.DottedNameField(choices=[(b'dummy', b'Dummy')], default='staszic.rankings.ranking_renderers.TableRenderer', superclass='staszic.rankings.ranking_renderers.RankingRendererBase'),
            preserve_default=False,
        ),
    ]
