# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_staszicranking_renderer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryRankingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_sum', models.BooleanField(default=True)),
                ('show_percentage', models.BooleanField(default=False)),
                ('show_difference', models.BooleanField(default=False)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
    ]
