# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_summaryrankingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRendererConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medals', models.CharField(choices=[('none', 'No medals'), ('ioi', 'IOI - 1/12 golds, 1/6 silver, 1/4 bronze'), ('og', '1 gold, 1 silver, 1 bronze')], default='none', max_length=8)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
    ]
