# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_tablerendererconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrankingconfig',
            name='column_visibility',
            field=models.CharField(choices=[('never', 'Never visible'), ('end', 'Visible after the round ends'), ('results', 'Visible as the round results become visible'), ('always', 'Visible after the round starts')], default='end', max_length=8),
        ),
    ]
