# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20180825_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRoundRankingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_coef', models.IntegerField(default=1, verbose_name='Contest coefficient')),
                ('round_type', models.CharField(choices=[('best', 'Best'), ('last', 'Last'), ('rlast', 'Last + revealed')], default='last', max_length=8, verbose_name='Contest scoring type')),
                ('contest_coef', models.IntegerField(default=0, verbose_name='All-time coefficient')),
                ('contest_type', models.CharField(choices=[('best', 'Best'), ('last', 'Last'), ('rlast', 'Last + revealed')], default='best', max_length=8, verbose_name='All-time scoring type')),
                ('column_visibility', models.CharField(choices=[('never', 'Never visible'), ('end', 'Visible after the round ends'), ('results', 'Visible as the round results become visible'), ('always', 'Visible after the round starts')], default='end', max_length=8)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
    ]
