# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20180824_1612'),
        ('rankings', '0007_multiroundrankingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundInRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Round')),
            ],
        ),
    ]
