# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_roundinranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundinranking',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking'),
        ),
    ]
