# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_auto_20190126_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRankingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.TextField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
    ]
