# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20190128_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicranking',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
