# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0012_staszicranking_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', oioioi.base.fields.DottedNameField(choices=[(b'dummy', b'Dummy')], superclass='staszic.rankings.ranking_filter.RankingFilterBase')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.StaszicRanking')),
            ],
        ),
        migrations.CreateModel(
            name='TimeFilterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('mode', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=8)),
            ],
        ),
    ]
