# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-11 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_submission_auto_rejudges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rankings', '0013_rankingfilter_timefilterconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_scores', models.BooleanField(default=False, verbose_name='Hide scores')),
                ('hide_name', models.BooleanField(default=False, verbose_name='Hide name')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rankingfilter',
            name='ranking',
        ),
        migrations.DeleteModel(
            name='TimeFilterConfig',
        ),
        migrations.DeleteModel(
            name='RankingFilter',
        ),
    ]
