# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_auto_20190811_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrankingconfig',
            name='order',
            field=models.CharField(choices=[('max', 'maximum score'), ('min', 'minimum score')], default='max', max_length=3, verbose_name='Best solution'),
        ),
    ]
