# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_roundrankingconfig_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiroundrankingconfig',
            name='ignore_submissions_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ignore submissions after'),
        ),
    ]
