# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-07 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0009_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='duration in minutes')),
                ('difficulty', models.IntegerField()),
                ('description', models.TextField()),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Round')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualContestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.VirtualContest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
