# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_auto_20180816_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stderr_visible', models.BooleanField(default=False)),
                ('comment_visible', models.BooleanField(default=False)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
            options={
                'verbose_name': 'report elements visible for the participant',
                'verbose_name_plural': 'report elements visible for the participant',
            },
        ),
    ]
