# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='comment_visible',
            field=models.BooleanField(default=True),
        ),
    ]
