# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-25 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180725_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='element',
            field=models.CharField(default='', max_length=64),
        ),
    ]
