# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-26 07:30
from __future__ import unicode_literals

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180725_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='element',
            field=oioioi.base.fields.EnumField(max_length=64, verbose_name='report element'),
        ),
    ]
