# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180726_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportconfig',
            name='element',
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='comment_visible',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='stderr_visible',
            field=models.NullBooleanField(default=False),
        ),
    ]
