# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oioioi.base.fields
import oioioi.filetracker.fields
import staszic.archive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicOldContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('name', models.CharField(max_length=512)),
                ('sio2dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldContestAdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest')),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(default=0)),
                ('short_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('package', models.FileField(blank=True, default=None, null=True, upload_to=staszic.archive.models.make_problem_filename)),
                ('statement', models.FileField(blank=True, default=None, null=True, upload_to=staszic.archive.models.make_problem_filename)),
                ('sio2dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldProblemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=512)),
                ('contest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest')),
                ('problem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblem')),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', oioioi.base.fields.EnumField(max_length=64)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('source', oioioi.filetracker.fields.FileField(blank=True, default=None, max_length=255, null=True, upload_to=staszic.archive.models.make_submission_filename)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('is_superuser', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldUser'),
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='problem_instance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblemInstance'),
        ),
        migrations.AddField(
            model_name='staszicoldcontestadminpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldUser'),
        ),
    ]
