# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicOldContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', oioioi.base.fields.EnumField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldUser'),
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest'),
        ),
    ]
