# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldprobleminstance',
            name='piid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
