# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20180603_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staszicolduser',
            name='parent',
        ),
    ]
