# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0004_remove_staszicolduser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicolduser',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
