# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_staszicolduser_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicOldContestAdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StaszicOldProblemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='staszicoldcontest',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='staszicoldprobleminstance',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest'),
        ),
        migrations.AddField(
            model_name='staszicoldcontestadminpermission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest'),
        ),
        migrations.AddField(
            model_name='staszicoldcontestadminpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldUser'),
        ),
    ]
