# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20180603_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staszicoldsubmission',
            name='contest',
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='problem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblemInstance'),
        ),
    ]
