# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20180603_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicOldProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='staszicoldprobleminstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staszicoldprobleminstance',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='staszicoldprobleminstance',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest'),
        ),
        migrations.AddField(
            model_name='staszicoldprobleminstance',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblem'),
        ),
    ]
