# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20180603_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
