# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_staszicoldsubmission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staszicoldprobleminstance',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='staszicoldprobleminstance',
            name='problem',
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest'),
        ),
        migrations.AlterField(
            model_name='staszicoldsubmission',
            name='problem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblem'),
        ),
        migrations.DeleteModel(
            name='StaszicOldProblemInstance',
        ),
    ]
