# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20180604_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaszicOldProblemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=512)),
                ('contest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldContest')),
                ('problem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldProblem')),
            ],
        ),
    ]
