# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20180606_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staszicoldsubmission',
            name='contest',
        ),
    ]
