# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_remove_staszicoldsubmission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldproblem',
            name='problem_id',
            field=models.IntegerField(default=0),
        ),
    ]
