# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_staszicoldproblem_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staszicoldsubmission',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.StaszicOldUser'),
        ),
    ]
