# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20180606_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staszicoldsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
