# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20180606_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldcontest',
            name='sio2dead',
            field=models.BooleanField(default=False),
        ),
    ]
