# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-14 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import staszic.archive.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_staszicoldproblem_sio2dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldproblem',
            name='statement',
            field=models.FileField(blank=True, default=None, null=True, upload_to=staszic.archive.models.make_problem_filename),
        ),
    ]
