# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import oioioi.filetracker.fields
import staszic.archive.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_staszicoldproblem_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='statement',
            field=oioioi.filetracker.fields.FileField(blank=True, default=None, max_length=255, null=True, upload_to=staszic.archive.models.make_submission_filename),
        ),
        migrations.AddField(
            model_name='staszicoldsubmission',
            name='submission_id',
            field=models.IntegerField(default=0),
        ),
    ]
