# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20180705_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staszicoldsubmission',
            old_name='statement',
            new_name='source',
        ),
    ]
