# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\"9\n\x14GetSubmissionRequest\x12\x0f\n\x07\x63ontest\x18\x01 \x01(\t\x12\x10\n\x08problems\x18\x02 \x03(\t\"[\n\x15GetSubmissionResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07problem\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x13\n\x0bsource_code\x18\x03 \x01(\x0c\"\x8a\x02\n\x12PostResultsRequest\x12\x15\n\rsubmission_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x66\x61ilure_text\x18\t \x01(\t\x12\x17\n\x06status\x18\x02 \x01(\x0e\x32\x07.Status\x12\x17\n\x0f\x63ompiler_output\x18\x03 \x01(\t\x12\x11\n\thas_score\x18\n \x01(\x08\x12\r\n\x05score\x18\x04 \x01(\x03\x12\x15\n\rhas_max_score\x18\x0b \x01(\x08\x12\x11\n\tmax_score\x18\x05 \x01(\x03\x12\x1c\n\x06groups\x18\x06 \x03(\x0b\x32\x0c.GroupResult\x12\x1a\n\x05tests\x18\x07 \x03(\x0b\x32\x0b.TestResult\x12\x0f\n\x07\x63omment\x18\x08 \x01(\t\"\x15\n\x13PostResultsResponse\"\xa1\x01\n\nTestResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x12\n\ntime_limit\x18\x03 \x01(\x03\x12\x11\n\tmax_score\x18\x04 \x01(\x03\x12\x17\n\x06status\x18\x05 \x01(\x0e\x32\x07.Status\x12\r\n\x05score\x18\x06 \x01(\x03\x12\x11\n\ttime_used\x18\x07 \x01(\x03\x12\x0f\n\x07\x63omment\x18\x08 \x01(\t\"V\n\x0bGroupResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x03\x12\x11\n\tmax_score\x18\x03 \x01(\x03\x12\x17\n\x06status\x18\x04 \x01(\x0e\x32\x07.Status*h\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x06\n\x02WA\x10\x02\x12\x06\n\x02RE\x10\x03\x12\x07\n\x03TLE\x10\x04\x12\x07\n\x03MLE\x10\x05\x12\x07\n\x03OLE\x10\x06\x12\x06\n\x02SE\x10\x07\x12\x06\n\x02RV\x10\x08\x12\x06\n\x02\x43\x45\x10\t\x12\x06\n\x02NJ\x10\nb\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TLE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MLE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OLE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RV', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NJ', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=709,
  serialized_end=813,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
OK = 1
WA = 2
RE = 3
TLE = 4
MLE = 5
OLE = 6
SE = 7
RV = 8
CE = 9
NJ = 10



_GETSUBMISSIONREQUEST = _descriptor.Descriptor(
  name='GetSubmissionRequest',
  full_name='GetSubmissionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contest', full_name='GetSubmissionRequest.contest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='problems', full_name='GetSubmissionRequest.problems', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=70,
)


_GETSUBMISSIONRESPONSE = _descriptor.Descriptor(
  name='GetSubmissionResponse',
  full_name='GetSubmissionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetSubmissionResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='problem', full_name='GetSubmissionResponse.problem', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='GetSubmissionResponse.language', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_code', full_name='GetSubmissionResponse.source_code', index=3,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=163,
)


_POSTRESULTSREQUEST = _descriptor.Descriptor(
  name='PostResultsRequest',
  full_name='PostResultsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='submission_id', full_name='PostResultsRequest.submission_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_text', full_name='PostResultsRequest.failure_text', index=1,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='PostResultsRequest.status', index=2,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compiler_output', full_name='PostResultsRequest.compiler_output', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_score', full_name='PostResultsRequest.has_score', index=4,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='PostResultsRequest.score', index=5,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_max_score', full_name='PostResultsRequest.has_max_score', index=6,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_score', full_name='PostResultsRequest.max_score', index=7,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='PostResultsRequest.groups', index=8,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tests', full_name='PostResultsRequest.tests', index=9,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='PostResultsRequest.comment', index=10,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=432,
)


_POSTRESULTSRESPONSE = _descriptor.Descriptor(
  name='PostResultsResponse',
  full_name='PostResultsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=455,
)


_TESTRESULT = _descriptor.Descriptor(
  name='TestResult',
  full_name='TestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TestResult.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='TestResult.group_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_limit', full_name='TestResult.time_limit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_score', full_name='TestResult.max_score', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='TestResult.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='TestResult.score', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_used', full_name='TestResult.time_used', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='TestResult.comment', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=619,
)


_GROUPRESULT = _descriptor.Descriptor(
  name='GroupResult',
  full_name='GroupResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GroupResult.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='GroupResult.score', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_score', full_name='GroupResult.max_score', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GroupResult.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=707,
)

_POSTRESULTSREQUEST.fields_by_name['status'].enum_type = _STATUS
_POSTRESULTSREQUEST.fields_by_name['groups'].message_type = _GROUPRESULT
_POSTRESULTSREQUEST.fields_by_name['tests'].message_type = _TESTRESULT
_TESTRESULT.fields_by_name['status'].enum_type = _STATUS
_GROUPRESULT.fields_by_name['status'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['GetSubmissionRequest'] = _GETSUBMISSIONREQUEST
DESCRIPTOR.message_types_by_name['GetSubmissionResponse'] = _GETSUBMISSIONRESPONSE
DESCRIPTOR.message_types_by_name['PostResultsRequest'] = _POSTRESULTSREQUEST
DESCRIPTOR.message_types_by_name['PostResultsResponse'] = _POSTRESULTSRESPONSE
DESCRIPTOR.message_types_by_name['TestResult'] = _TESTRESULT
DESCRIPTOR.message_types_by_name['GroupResult'] = _GROUPRESULT
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSubmissionRequest = _reflection.GeneratedProtocolMessageType('GetSubmissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBMISSIONREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:GetSubmissionRequest)
  })
_sym_db.RegisterMessage(GetSubmissionRequest)

GetSubmissionResponse = _reflection.GeneratedProtocolMessageType('GetSubmissionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBMISSIONRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:GetSubmissionResponse)
  })
_sym_db.RegisterMessage(GetSubmissionResponse)

PostResultsRequest = _reflection.GeneratedProtocolMessageType('PostResultsRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTRESULTSREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:PostResultsRequest)
  })
_sym_db.RegisterMessage(PostResultsRequest)

PostResultsResponse = _reflection.GeneratedProtocolMessageType('PostResultsResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSTRESULTSRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:PostResultsResponse)
  })
_sym_db.RegisterMessage(PostResultsResponse)

TestResult = _reflection.GeneratedProtocolMessageType('TestResult', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESULT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:TestResult)
  })
_sym_db.RegisterMessage(TestResult)

GroupResult = _reflection.GeneratedProtocolMessageType('GroupResult', (_message.Message,), {
  'DESCRIPTOR' : _GROUPRESULT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:GroupResult)
  })
_sym_db.RegisterMessage(GroupResult)


# @@protoc_insertion_point(module_scope)
