# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0004_auto_20180824_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('contest', models.ManyToManyField(to='contests.Contest')),
                ('parent_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.ContestGroup')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
