# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_submission_auto_rejudges'),
        ('lessons', '0002_auto_20191015_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmissionCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originals', to='contests.Submission')),
                ('original_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='contests.Submission')),
            ],
        ),
    ]
